# Generated by Django 4.2.7 on 2023-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
