# Generated by Django 4.2.7 on 2023-11-21 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
