# Generated by Django 4.2.7 on 2023-11-21 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
