# Generated by Django 4.2.7 on 2023-11-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
