# Generated by Django 4.2.7 on 2023-11-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
    ]
