# Generated by Django 4.2.7 on 2023-11-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
